#serie_data_homepage:
 #   path:     /load
  #  defaults: { _controller: DataBundle:LoadData:addSeriess }

#serie_data_formpage:
 #   path:     /form
  #  defaults: { _controller: DataBundle:Serie:form }

#serie_data_formnewserie:
 #   path:     /search-serie
  #  defaults: { _controller: DataBundle:LoadData:addSeries }
   # options:
    #    expose: true

#serie_data_getserie:
 #   path:     /get_serie
  #  defaults: { _controller: DataBundle:Serie:getSerie }
   # options:
    #    expose: true

#serie_data_getseriesfilter:
 #   path:     /get_series_filter
  #  defaults: { _controller: DataBundle:Serie:getSeriesFilter }
   # options:
    #    expose: true