function autocomplete_data()
{
  $(function() {
    var availableTags = [
					{ value : 'Wayward Pines', label : 'Wayward Pines', slug : 'wayward-pines', icon : '/Symfony2/web/upload/poster/posters/269750-6.jpg' },
			  				{ value : 'Narcos', label : 'Narcos', slug : 'narcos', icon : '/Symfony2/web/upload/poster/posters/282670-8.jpg' },
			  				{ value : 'How I Met Your Mother', label : 'How I Met Your Mother', slug : 'how-i-met-your-mother', icon : '/Symfony2/web/upload/poster/posters/75760-34.jpg' },
			  				{ value : 'The Big Bang Theory', label : 'The Big Bang Theory', slug : 'the-big-bang-theory', icon : '/Symfony2/web/upload/poster/posters/80379-39.jpg' },
			  				{ value : 'Arrow', label : 'Arrow', slug : 'arrow', icon : '/Symfony2/web/upload/poster/posters/257655-27.jpg' },
			  				{ value : 'The Black Arrow', label : 'The Black Arrow', slug : 'the-black-arrow', icon : '/Symfony2/web/upload/poster/posters/252373-1.jpg' },
			  				{ value : 'Broken Arrow', label : 'Broken Arrow', slug : 'broken-arrow', icon : '/Symfony2/web/upload/poster/posters/70767-1.jpg' },
			  				{ value : 'Prison Break', label : 'Prison Break', slug : 'prison-break', icon : '/Symfony2/web/upload/poster/posters/75340-1.jpg' },
			  				{ value : 'Under the Dome', label : 'Under the Dome', slug : 'under-the-dome', icon : '/Symfony2/web/upload/poster/posters/264492-2.jpg' },
			  				{ value : 'Scrubs', label : 'Scrubs', slug : 'scrubs', icon : '/Symfony2/web/upload/poster/posters/76156-6.jpg' },
			  				{ value : 'Fargo', label : 'Fargo', slug : 'fargo', icon : '/Symfony2/web/upload/poster/posters/269613-12.jpg' },
			  				{ value : 'Tales of Wells Fargo', label : 'Tales of Wells Fargo', slug : 'tales-of-wells-fargo', icon : '/Symfony2/web/upload/poster/posters/76545-1.jpg' },
			  				{ value : 'True Detective', label : 'True Detective', slug : 'true-detective', icon : '/Symfony2/web/upload/poster/posters/270633-3.jpg' },
			  				{ value : 'Person of Interest', label : 'Person of Interest', slug : 'person-of-interest', icon : '/Symfony2/web/upload/poster/posters/248742-15.jpg' },
			  				{ value : 'Blacklist', label : 'Blacklist', slug : 'blacklist', icon : '/Symfony2/web/upload/poster/posters/266189-14.jpg' },
			  				{ value : 'Game of Thrones', label : 'Game of Thrones', slug : 'game-of-thrones', icon : '/Symfony2/web/upload/poster/posters/121361-34.jpg' },
			  				{ value : 'American Dad!', label : 'American Dad!', slug : 'american-dad', icon : '/Symfony2/web/upload/poster/posters/73141-8.jpg' },
			  				{ value : 'Blue Mountain State', label : 'Blue Mountain State', slug : 'blue-mountain-state', icon : '/Symfony2/web/upload/poster/posters/134511-5.jpg' },
			  				{ value : 'Les Experts', label : 'Les Experts', slug : 'les-experts', icon : '/Symfony2/web/upload/poster/posters/72546-8.jpg' },
			  				{ value : 'Les Experts : Manhattan', label : 'Les Experts : Manhattan', slug : 'les-experts-manhattan', icon : '/Symfony2/web/upload/poster/posters/73696-3.jpg' },
			  				{ value : 'Jurassic CSI', label : 'Jurassic CSI', slug : 'jurassic-csi', icon : '/Symfony2/web/upload/poster/posters/253030-1.jpg' },
			  				{ value : 'Edward and Mrs Simpson', label : 'Edward and Mrs Simpson', slug : 'edward-and-mrs-simpson', icon : '/Symfony2/web/upload/poster/posters/70982-1.jpg' },
			  				{ value : 'The Galton and Simpson Playhouse (1969)', label : 'The Galton and Simpson Playhouse (1969)', slug : 'the-galton-and-simpson-playhouse-1969', icon : '/Symfony2/web/upload/poster/default/the-galton-and-simpson-playhouse-1969.jpg' },
			  				{ value : 'Paul Merton in Galton &amp; Simpson&#039;s...', label : 'Paul Merton in Galton &amp; Simpson&#039;s...', slug : 'paul-merton-in-galton-simpson-s', icon : '/Symfony2/web/upload/poster/default/paul-merton-in-galton-simpson-s.jpg' },
			  				{ value : 'Les Simpson', label : 'Les Simpson', slug : 'les-simpson', icon : '/Symfony2/web/upload/poster/posters/71663-10.jpg' },
			  				{ value : 'Jessica Simpson&#039;s The Price of Beauty', label : 'Jessica Simpson&#039;s The Price of Beauty', slug : 'jessica-simpson-s-the-price-of-beauty', icon : '/Symfony2/web/upload/poster/posters/153221-1.jpg' },
			  				{ value : 'Zorro and Son', label : 'Zorro and Son', slug : 'zorro-and-son', icon : '/Symfony2/web/upload/poster/default/zorro-and-son.jpg' },
			  				{ value : 'Son of Zorro', label : 'Son of Zorro', slug : 'son-of-zorro', icon : '/Symfony2/web/upload/poster/posters/253804-1.jpg' },
			  				{ value : 'Zorro Rides Again', label : 'Zorro Rides Again', slug : 'zorro-rides-again', icon : '/Symfony2/web/upload/poster/posters/253813-1.jpg' },
			  				{ value : 'Ghost of Zorro', label : 'Ghost of Zorro', slug : 'ghost-of-zorro', icon : '/Symfony2/web/upload/poster/posters/254209-1.jpg' },
			  				{ value : 'Zorro (1957)', label : 'Zorro (1957)', slug : 'zorro-1957', icon : '/Symfony2/web/upload/poster/posters/74683-4.jpg' },
			  				{ value : 'Zorro', label : 'Zorro', slug : 'zorro', icon : '/Symfony2/web/upload/poster/posters/78737-1.jpg' },
			  				{ value : 'Zorro: Generation Z', label : 'Zorro: Generation Z', slug : 'zorro-generation-z', icon : '/Symfony2/web/upload/poster/default/zorro-generation-z.jpg' },
			  				{ value : 'Les Nouvelles Aventures de Zorro', label : 'Les Nouvelles Aventures de Zorro', slug : 'les-nouvelles-aventures-de-zorro', icon : '/Symfony2/web/upload/poster/posters/73662-2.jpg' },
			  				{ value : 'La légende de Zorro', label : 'La légende de Zorro', slug : 'la-legende-de-zorro', icon : '/Symfony2/web/upload/poster/posters/250582-2.jpg' },
			  				{ value : 'Les chroniques de Zorro', label : 'Les chroniques de Zorro', slug : 'les-chroniques-de-zorro', icon : '/Symfony2/web/upload/poster/posters/302104-1.jpg' },
			  				{ value : 'Zorro (1997)', label : 'Zorro (1997)', slug : 'zorro-1997', icon : '/Symfony2/web/upload/poster/default/zorro-1997.jpg' },
			  				{ value : 'American Crime Story', label : 'American Crime Story', slug : 'american-crime-story', icon : '/Symfony2/web/upload/poster/posters/289108-1.jpg' },
			  				{ value : 'Desperate Housewives', label : 'Desperate Housewives', slug : 'desperate-housewives', icon : '/Symfony2/web/upload/poster/posters/73800-9.jpg' },
			  				{ value : 'Showman', label : 'Showman', slug : 'showman', icon : '/Symfony2/web/upload/poster/default/showman.jpg' },
			  				{ value : 'Pompei', label : 'Pompei', slug : 'pompei', icon : '/Symfony2/web/upload/poster/posters/248928-1.jpg' },
			  				{ value : '40', label : '40', slug : '40', icon : '/Symfony2/web/upload/poster/posters/82346-1.jpg' },
			  				{ value : 'Ghostrider', label : 'Ghostrider', slug : 'ghostrider', icon : '/Symfony2/web/upload/poster/default/ghostrider.jpg' },
			  				{ value : 'BSGCast', label : 'BSGCast', slug : 'bsgcast', icon : '/Symfony2/web/upload/poster/default/bsgcast.jpg' },
			  				{ value : 'Gekikoi', label : 'Gekikoi', slug : 'gekikoi', icon : '/Symfony2/web/upload/poster/default/gekikoi.jpg' },
			  				{ value : 'Checkmate', label : 'Checkmate', slug : 'checkmate', icon : '/Symfony2/web/upload/poster/default/checkmate.jpg' },
			  				{ value : 'Suspect', label : 'Suspect', slug : 'suspect', icon : '/Symfony2/web/upload/poster/default/suspect.jpg' },
			  				{ value : 'Masterwork', label : 'Masterwork', slug : 'masterwork', icon : '/Symfony2/web/upload/poster/default/masterwork.jpg' },
			  				{ value : 'Blade', label : 'Blade', slug : 'blade', icon : '/Symfony2/web/upload/poster/posters/73192-4.jpg' },
			  				{ value : 'Cantor', label : 'Cantor', slug : 'cantor', icon : '/Symfony2/web/upload/poster/posters/180061-1.jpg' },
			  				{ value : 'Kirepapa', label : 'Kirepapa', slug : 'kirepapa', icon : '/Symfony2/web/upload/poster/default/kirepapa.jpg' },
			  				{ value : 'Troopers', label : 'Troopers', slug : 'troopers', icon : '/Symfony2/web/upload/poster/posters/240431-1.jpg' },
			  				{ value : 'Hameraglim', label : 'Hameraglim', slug : 'hameraglim', icon : '/Symfony2/web/upload/poster/posters/248974-1.jpg' },
			  				{ value : 'Duggan', label : 'Duggan', slug : 'duggan', icon : '/Symfony2/web/upload/poster/default/duggan.jpg' },
			  				{ value : 'Simon', label : 'Simon', slug : 'simon', icon : '/Symfony2/web/upload/poster/default/simon.jpg' },
			  				{ value : 'Clémentine', label : 'Clémentine', slug : 'clementine', icon : '/Symfony2/web/upload/poster/posters/79792-1.jpg' },
			  				{ value : 'Pinks', label : 'Pinks', slug : 'pinks', icon : '/Symfony2/web/upload/poster/posters/82265-1.jpg' },
			  				{ value : 'Pagans', label : 'Pagans', slug : 'pagans', icon : '/Symfony2/web/upload/poster/posters/82255-2.jpg' },
			  				{ value : 'Maysa', label : 'Maysa', slug : 'maysa', icon : '/Symfony2/web/upload/poster/posters/96041-1.jpg' },
			  				{ value : 'Thwackers', label : 'Thwackers', slug : 'thwackers', icon : '/Symfony2/web/upload/poster/posters/124681-1.jpg' },
			  				{ value : 'Wasted', label : 'Wasted', slug : 'wasted', icon : '/Symfony2/web/upload/poster/default/wasted.jpg' },
			  				{ value : 'Wholphin', label : 'Wholphin', slug : 'wholphin', icon : '/Symfony2/web/upload/poster/default/wholphin.jpg' },
			  				{ value : 'videoGaiden', label : 'videoGaiden', slug : 'videogaiden', icon : '/Symfony2/web/upload/poster/posters/79819-1.jpg' },
			  				{ value : 'Invisible', label : 'Invisible', slug : 'invisible', icon : '/Symfony2/web/upload/poster/default/invisible.jpg' },
			  				{ value : 'CapriCast', label : 'CapriCast', slug : 'capricast', icon : '/Symfony2/web/upload/poster/default/capricast.jpg' },
			  				{ value : 'Kablam!', label : 'Kablam!', slug : 'kablam', icon : '/Symfony2/web/upload/poster/posters/77191-2.jpg' },
			  				{ value : '1821', label : '1821', slug : '1821', icon : '/Symfony2/web/upload/poster/posters/240111-1.jpg' },
			  				{ value : 'Inoe', label : 'Inoe', slug : 'inoe', icon : '/Symfony2/web/upload/poster/default/inoe.jpg' },
			  				{ value : 'Usavich', label : 'Usavich', slug : 'usavich', icon : '/Symfony2/web/upload/poster/posters/137951-1.jpg' },
			  				{ value : 'Coolman!', label : 'Coolman!', slug : 'coolman', icon : '/Symfony2/web/upload/poster/default/coolman.jpg' },
			  				{ value : 'Spencer', label : 'Spencer', slug : 'spencer', icon : '/Symfony2/web/upload/poster/default/spencer.jpg' },
			  				{ value : 'Northwood', label : 'Northwood', slug : 'northwood', icon : '/Symfony2/web/upload/poster/default/northwood.jpg' },
			  				{ value : 'Gloria', label : 'Gloria', slug : 'gloria', icon : '/Symfony2/web/upload/poster/default/gloria.jpg' },
			  				{ value : 'Marker', label : 'Marker', slug : 'marker', icon : '/Symfony2/web/upload/poster/posters/78327-1.jpg' },
			  				{ value : 'Newstopia', label : 'Newstopia', slug : 'newstopia', icon : '/Symfony2/web/upload/poster/posters/80696-1.jpg' },
			  				{ value : 'Dubbat', label : 'Dubbat', slug : 'dubbat', icon : '/Symfony2/web/upload/poster/posters/81387-1.jpg' },
			  				{ value : 'Historyonics', label : 'Historyonics', slug : 'historyonics', icon : '/Symfony2/web/upload/poster/default/historyonics.jpg' },
			  				{ value : 'Evelien', label : 'Evelien', slug : 'evelien', icon : '/Symfony2/web/upload/poster/default/evelien.jpg' },
			  				{ value : 'Kittens', label : 'Kittens', slug : 'kittens', icon : '/Symfony2/web/upload/poster/default/kittens.jpg' },
			  				{ value : 'Jabo0odyDubs', label : 'Jabo0odyDubs', slug : 'jabo0odydubs', icon : '/Symfony2/web/upload/poster/default/jabo0odydubs.jpg' },
			  				{ value : 'Verminators', label : 'Verminators', slug : 'verminators', icon : '/Symfony2/web/upload/poster/default/verminators.jpg' },
			  				{ value : 'crimini', label : 'crimini', slug : 'crimini', icon : '/Symfony2/web/upload/poster/posters/82710-1.jpg' },
			  				{ value : 'Loss:Time:Life', label : 'Loss:Time:Life', slug : 'loss-time-life', icon : '/Symfony2/web/upload/poster/default/loss-time-life.jpg' },
			  				{ value : 'Madita', label : 'Madita', slug : 'madita', icon : '/Symfony2/web/upload/poster/posters/93521-1.jpg' },
			  				{ value : 'Mayo', label : 'Mayo', slug : 'mayo', icon : '/Symfony2/web/upload/poster/posters/82338-1.jpg' },
			  				{ value : 'Kokoda', label : 'Kokoda', slug : 'kokoda', icon : '/Symfony2/web/upload/poster/posters/163631-1.jpg' },
			  				{ value : 'Moana', label : 'Moana', slug : 'moana', icon : '/Symfony2/web/upload/poster/posters/127101-1.jpg' },
			  				{ value : 'Stankervision', label : 'Stankervision', slug : 'stankervision', icon : '/Symfony2/web/upload/poster/default/stankervision.jpg' },
			  				{ value : 'Lost, les disparus', label : 'Lost, les disparus', slug : 'lost-les-disparus', icon : '/Symfony2/web/upload/poster/posters/73739-11.jpg' },
			  				{ value : 'Lost Empires', label : 'Lost Empires', slug : 'lost-empires', icon : '/Symfony2/web/upload/poster/posters/250364-1.jpg' },
			  				{ value : 'Lost (UK)', label : 'Lost (UK)', slug : 'lost-uk', icon : '/Symfony2/web/upload/poster/default/lost-uk.jpg' },
			  				{ value : 'Lost (2001)', label : 'Lost (2001)', slug : 'lost-2001', icon : '/Symfony2/web/upload/poster/default/lost-2001.jpg' },
			  				{ value : 'Sora no Otoshimono', label : 'Sora no Otoshimono', slug : 'sora-no-otoshimono', icon : '/Symfony2/web/upload/poster/posters/118101-9.jpg' },
			  				{ value : 'Spain - Paradise Lost', label : 'Spain - Paradise Lost', slug : 'spain-paradise-lost', icon : '/Symfony2/web/upload/poster/posters/160821-1.jpg' },
			  				{ value : 'Lost Worlds, Vanished Lives', label : 'Lost Worlds, Vanished Lives', slug : 'lost-worlds-vanished-lives', icon : '/Symfony2/web/upload/poster/posters/79616-1.jpg' },
			  				{ value : 'Mob City', label : 'Mob City', slug : 'mob-city', icon : '/Symfony2/web/upload/poster/posters/259632-3.jpg' },
			  				{ value : 'R.I.S Police Scientifique', label : 'R.I.S Police Scientifique', slug : 'r-i-s-police-scientifique', icon : '/Symfony2/web/upload/poster/posters/81685-1.jpg' },
			  				{ value : 'Les Spécialistes', label : 'Les Spécialistes', slug : 'les-specialistes', icon : '/Symfony2/web/upload/poster/posters/81642-1.jpg' },
			  				{ value : 'R.I.S Científica', label : 'R.I.S Científica', slug : 'r-i-s-cientifica', icon : '/Symfony2/web/upload/poster/posters/123211-1.jpg' },
			  				{ value : 'Saxondale', label : 'Saxondale', slug : 'saxondale', icon : '/Symfony2/web/upload/poster/posters/79517-2.jpg' },
			  				{ value : 'Plea', label : 'Plea', slug : 'plea', icon : '/Symfony2/web/upload/poster/posters/190581-1.jpg' },
			  				{ value : 'Karusel', label : 'Karusel', slug : 'karusel', icon : '/Symfony2/web/upload/poster/posters/199671-1.jpg' },
			  				{ value : 'Reptiles', label : 'Reptiles', slug : 'reptiles', icon : '/Symfony2/web/upload/poster/posters/206841-1.jpg' },
			  				{ value : 'Dalnoboyshchiki', label : 'Dalnoboyshchiki', slug : 'dalnoboyshchiki', icon : '/Symfony2/web/upload/poster/posters/145261-1.jpg' },
			  				{ value : 'Notorious', label : 'Notorious', slug : 'notorious', icon : '/Symfony2/web/upload/poster/default/notorious.jpg' },
			  				{ value : 'Rytteriet', label : 'Rytteriet', slug : 'rytteriet', icon : '/Symfony2/web/upload/poster/posters/205651-1.jpg' },
			  				{ value : 'Click', label : 'Click', slug : 'click', icon : '/Symfony2/web/upload/poster/default/click.jpg' },
			  				{ value : 'Coachella', label : 'Coachella', slug : 'coachella', icon : '/Symfony2/web/upload/poster/posters/248244-2.jpg' },
			  				{ value : 'Carriers', label : 'Carriers', slug : 'carriers', icon : '/Symfony2/web/upload/poster/default/carriers.jpg' },
			  				{ value : 'Tekno', label : 'Tekno', slug : 'tekno', icon : '/Symfony2/web/upload/poster/posters/93231-1.jpg' },
			  				{ value : 'Powerhouse', label : 'Powerhouse', slug : 'powerhouse', icon : '/Symfony2/web/upload/poster/default/powerhouse.jpg' },
			  				{ value : 'Charlie', label : 'Charlie', slug : 'charlie', icon : '/Symfony2/web/upload/poster/default/charlie.jpg' },
			  				{ value : 'Spoofovision', label : 'Spoofovision', slug : 'spoofovision', icon : '/Symfony2/web/upload/poster/default/spoofovision.jpg' },
			  				{ value : 'Dreams', label : 'Dreams', slug : 'dreams', icon : '/Symfony2/web/upload/poster/default/dreams.jpg' },
			  				{ value : 'Markham', label : 'Markham', slug : 'markham', icon : '/Symfony2/web/upload/poster/default/markham.jpg' },
			  				{ value : 'Delta', label : 'Delta', slug : 'delta', icon : '/Symfony2/web/upload/poster/default/delta.jpg' },
			  				{ value : 'Rango', label : 'Rango', slug : 'rango', icon : '/Symfony2/web/upload/poster/default/rango.jpg' },
			  				{ value : 'Kodiak', label : 'Kodiak', slug : 'kodiak', icon : '/Symfony2/web/upload/poster/default/kodiak.jpg' },
			  				{ value : 'Wogan', label : 'Wogan', slug : 'wogan', icon : '/Symfony2/web/upload/poster/default/wogan.jpg' },
			  				{ value : 'R3', label : 'R3', slug : 'r3', icon : '/Symfony2/web/upload/poster/default/r3.jpg' },
			  				{ value : 'Cos', label : 'Cos', slug : 'cos', icon : '/Symfony2/web/upload/poster/default/cos.jpg' },
			  				{ value : 'Cheat', label : 'Cheat', slug : 'cheat', icon : '/Symfony2/web/upload/poster/default/cheat.jpg' },
			  				{ value : 'Vids', label : 'Vids', slug : 'vids', icon : '/Symfony2/web/upload/poster/posters/81210-1.jpg' },
			  				{ value : 'Trippin&#039;', label : 'Trippin&#039;', slug : 'trippin', icon : '/Symfony2/web/upload/poster/default/trippin.jpg' },
			  				{ value : 'Transito', label : 'Transito', slug : 'transito', icon : '/Symfony2/web/upload/poster/default/transito.jpg' },
			  				{ value : 'Janosik', label : 'Janosik', slug : 'janosik', icon : '/Symfony2/web/upload/poster/posters/81286-2.jpg' },
			  				{ value : 'Vikings', label : 'Vikings', slug : 'vikings', icon : '/Symfony2/web/upload/poster/posters/260449-8.jpg' },
			  				{ value : 'Tales of the Vikings', label : 'Tales of the Vikings', slug : 'tales-of-the-vikings', icon : '/Symfony2/web/upload/poster/default/tales-of-the-vikings.jpg' },
			  				{ value : 'Blood of the Vikings', label : 'Blood of the Vikings', slug : 'blood-of-the-vikings', icon : '/Symfony2/web/upload/poster/posters/79358-1.jpg' },
			  				{ value : 'Vikings (2012)', label : 'Vikings (2012)', slug : 'vikings-2012', icon : '/Symfony2/web/upload/poster/posters/262368-5.jpg' },
			  				{ value : '** 403 : série non autorisée **', label : '** 403 : série non autorisée **', slug : '403-serie-non-autorisee', icon : '/Symfony2/web/upload/poster/posters/219901-1.jpg' },
			  				{ value : 'The 100', label : 'The 100', slug : 'the-100', icon : '/Symfony2/web/upload/poster/posters/268592-16.jpg' },
			  				{ value : 'The 100 Lives of Black Jack Savage', label : 'The 100 Lives of Black Jack Savage', slug : 'the-100-lives-of-black-jack-savage', icon : '/Symfony2/web/upload/poster/default/the-100-lives-of-black-jack-savage.jpg' },
			  				{ value : 'The 100 Scariest Movie Moments', label : 'The 100 Scariest Movie Moments', slug : 'the-100-scariest-movie-moments', icon : '/Symfony2/web/upload/poster/default/the-100-scariest-movie-moments.jpg' },
			  				{ value : 'The Top 100: NFL&#039;s Greatest Players', label : 'The Top 100: NFL&#039;s Greatest Players', slug : 'the-top-100-nfl-s-greatest-players', icon : '/Symfony2/web/upload/poster/posters/188471-1.jpg' },
			  				{ value : 'The Ultimate 100 Greatest Fights', label : 'The Ultimate 100 Greatest Fights', slug : 'the-ultimate-100-greatest-fights', icon : '/Symfony2/web/upload/poster/posters/279372-2.jpg' },
			  				{ value : '100 Years – The Countdown', label : '100 Years – The Countdown', slug : '100-years-the-countdown', icon : '/Symfony2/web/upload/poster/posters/92111-2.jpg' },
			  				{ value : 'Ancient Apocalypse', label : 'Ancient Apocalypse', slug : 'ancient-apocalypse', icon : '/Symfony2/web/upload/poster/posters/80521-2.jpg' },
			  				{ value : ' Countdown to Apocalypse', label : ' Countdown to Apocalypse', slug : 'countdown-to-apocalypse', icon : '/Symfony2/web/upload/poster/posters/264079-1.jpg' },
			  				{ value : 'Apocalypse Zero', label : 'Apocalypse Zero', slug : 'apocalypse-zero', icon : '/Symfony2/web/upload/poster/posters/140551-1.jpg' },
			  				{ value : 'Apocalypse Man', label : 'Apocalypse Man', slug : 'apocalypse-man', icon : '/Symfony2/web/upload/poster/default/apocalypse-man.jpg' },
			  				{ value : 'Apocalypse Lane', label : 'Apocalypse Lane', slug : 'apocalypse-lane', icon : '/Symfony2/web/upload/poster/posters/277115-1.jpg' },
			  				{ value : 'Whoops Apocalypse', label : 'Whoops Apocalypse', slug : 'whoops-apocalypse', icon : '/Symfony2/web/upload/poster/posters/77812-1.jpg' },
			  				{ value : '1983: The Brink of Apocalypse', label : '1983: The Brink of Apocalypse', slug : '1983-the-brink-of-apocalypse', icon : '/Symfony2/web/upload/poster/posters/282094-1.jpg' },
			  				{ value : 'Surviving the Apocalypse', label : 'Surviving the Apocalypse', slug : 'surviving-the-apocalypse', icon : '/Symfony2/web/upload/poster/default/surviving-the-apocalypse.jpg' },
			  				{ value : 'Apocalypse 101', label : 'Apocalypse 101', slug : 'apocalypse-101', icon : '/Symfony2/web/upload/poster/posters/267973-1.jpg' },
			  				{ value : 'Soldiers of the Apocalypse', label : 'Soldiers of the Apocalypse', slug : 'soldiers-of-the-apocalypse', icon : '/Symfony2/web/upload/poster/default/soldiers-of-the-apocalypse.jpg' },
			  				{ value : 'Dawn of the Apocalypse', label : 'Dawn of the Apocalypse', slug : 'dawn-of-the-apocalypse', icon : '/Symfony2/web/upload/poster/default/dawn-of-the-apocalypse.jpg' },
			  				{ value : 'Apocalypse: Hitler', label : 'Apocalypse: Hitler', slug : 'apocalypse-hitler', icon : '/Symfony2/web/upload/poster/posters/253534-2.jpg' },
			  				{ value : 'You, Me and the Apocalypse', label : 'You, Me and the Apocalypse', slug : 'you-me-and-the-apocalypse', icon : '/Symfony2/web/upload/poster/posters/295677-1.jpg' },
			  				{ value : 'Apocalypse : La 2ème Guerre Mondiale', label : 'Apocalypse : La 2ème Guerre Mondiale', slug : 'apocalypse-la-2eme-guerre-mondiale', icon : '/Symfony2/web/upload/poster/posters/113371-5.jpg' },
			  				{ value : 'Apocalypse : Staline', label : 'Apocalypse : Staline', slug : 'apocalypse-staline', icon : '/Symfony2/web/upload/poster/posters/301991-1.jpg' },
			  				{ value : 'Apocalypse : La 1ère Guerre Mondiale', label : 'Apocalypse : La 1ère Guerre Mondiale', slug : 'apocalypse-la-1ere-guerre-mondiale', icon : '/Symfony2/web/upload/poster/posters/279519-1.jpg' },
			  				{ value : 'Once Upon A Time', label : 'Once Upon A Time', slug : 'once-upon-a-time', icon : '/Symfony2/web/upload/poster/default/once-upon-a-time.jpg' },
			  				{ value : 'Once Upon a Time in Beitou', label : 'Once Upon a Time in Beitou', slug : 'once-upon-a-time-in-beitou', icon : '/Symfony2/web/upload/poster/posters/278083-1.jpg' },
			  				{ value : 'Once Upon a Time', label : 'Once Upon a Time', slug : 'once-upon-a-time-1', icon : '/Symfony2/web/upload/poster/posters/248835-1.jpg' },
			  				{ value : 'Ugly Betty', label : 'Ugly Betty', slug : 'ugly-betty', icon : '/Symfony2/web/upload/poster/posters/79352-3.jpg' },
			  				{ value : 'I Am Betty, The Ugly', label : 'I Am Betty, The Ugly', slug : 'i-am-betty-the-ugly', icon : '/Symfony2/web/upload/poster/posters/157521-1.jpg' },
			  				{ value : 'Better Call Saul', label : 'Better Call Saul', slug : 'better-call-saul', icon : '/Symfony2/web/upload/poster/posters/273181-17.jpg' },
			  				{ value : 'Breaking Bad', label : 'Breaking Bad', slug : 'breaking-bad', icon : '/Symfony2/web/upload/poster/posters/81189-10.jpg' },
			  				{ value : 'Metastasis', label : 'Metastasis', slug : 'metastasis', icon : '/Symfony2/web/upload/poster/posters/273859-1.jpg' },
			  				{ value : 'Wormwood Scrubs', label : 'Wormwood Scrubs', slug : 'wormwood-scrubs', icon : '/Symfony2/web/upload/poster/default/.jpg' },
			  				{ value : 'Dragon Ball', label : 'Dragon Ball', slug : 'dragon-ball', icon : '/Symfony2/web/upload/poster/posters/76666-15.jpg' },
			  				{ value : 'Dragon Ball Z', label : 'Dragon Ball Z', slug : 'dragon-ball-z', icon : '/Symfony2/web/upload/poster/posters/81472-2.jpg' },
			  				{ value : 'Dragon Ball Kai', label : 'Dragon Ball Kai', slug : 'dragon-ball-kai', icon : '/Symfony2/web/upload/poster/posters/88031-6.jpg' },
			  				{ value : 'Dragon Ball Z Abridged', label : 'Dragon Ball Z Abridged', slug : 'dragon-ball-z-abridged', icon : '/Symfony2/web/upload/poster/posters/248580-1.jpg' },
			  				{ value : 'Dragon Ball Super', label : 'Dragon Ball Super', slug : 'dragon-ball-super', icon : '/Symfony2/web/upload/poster/posters/295068-2.jpg' },
			  				{ value : 'Marvel&#039;s Daredevil', label : 'Marvel&#039;s Daredevil', slug : 'marvel-s-daredevil', icon : '/Symfony2/web/upload/poster/posters/281662-17.jpg' },
			  				{ value : 'Braquo', label : 'Braquo', slug : 'braquo', icon : '/Symfony2/web/upload/poster/posters/118451-6.jpg' },
			  				{ value : 'The Walking Dead', label : 'The Walking Dead', slug : 'the-walking-dead', icon : '/Symfony2/web/upload/poster/posters/153021-31.jpg' },
			  				{ value : 'Fear the Walking Dead', label : 'Fear the Walking Dead', slug : 'fear-the-walking-dead', icon : '/Symfony2/web/upload/poster/posters/290853-6.jpg' },
			  				{ value : 'Dead End Express', label : 'Dead End Express', slug : 'dead-end-express', icon : '/Symfony2/web/upload/poster/default/.jpg' },
			  				{ value : 'Dead End', label : 'Dead End', slug : 'dead-end', icon : '/Symfony2/web/upload/poster/posters/282575-1.jpg' },
			  				{ value : 'Dead of Night', label : 'Dead of Night', slug : 'dead-of-night', icon : '/Symfony2/web/upload/poster/posters/70392-2.jpg' },
			  				{ value : 'Dead at 21', label : 'Dead at 21', slug : 'dead-at-21', icon : '/Symfony2/web/upload/poster/posters/75627-1.jpg' },
			  				{ value : 'Temps mort', label : 'Temps mort', slug : 'temps-mort', icon : '/Symfony2/web/upload/poster/posters/254725-1.jpg' },
			  				{ value : 'Dead Souls (1984)', label : 'Dead Souls (1984)', slug : 'dead-souls-1984', icon : '/Symfony2/web/upload/poster/posters/260997-1.jpg' },
			  				{ value : 'Talking Dead', label : 'Talking Dead', slug : 'talking-dead', icon : '/Symfony2/web/upload/poster/posters/252861-3.jpg' },
			  				{ value : 'Highschool of the Dead', label : 'Highschool of the Dead', slug : 'highschool-of-the-dead', icon : '/Symfony2/web/upload/poster/posters/171591-9.jpg' },
			  				{ value : 'Ash vs Evil Dead', label : 'Ash vs Evil Dead', slug : 'ash-vs-evil-dead', icon : '/Symfony2/web/upload/poster/posters/296295-2.jpg' },
			  				{ value : 'La Loi du Colt', label : 'La Loi du Colt', slug : 'la-loi-du-colt', icon : '/Symfony2/web/upload/poster/posters/73600-3.jpg' },
			  				{ value : 'Dead Man&#039;s Walk', label : 'Dead Man&#039;s Walk', slug : 'dead-man-s-walk', icon : '/Symfony2/web/upload/poster/posters/80307-1.jpg' },
			  				{ value : 'Dead Men&#039;s Secrets', label : 'Dead Men&#039;s Secrets', slug : 'dead-men-s-secrets', icon : '/Symfony2/web/upload/poster/posters/264918-2.jpg' },
			  				{ value : 'Kore wa Zombie desu ka', label : 'Kore wa Zombie desu ka', slug : 'kore-wa-zombie-desu-ka', icon : '/Symfony2/web/upload/poster/posters/220571-4.jpg' },
			  				{ value : 'Bonnie &amp; Clyde', label : 'Bonnie &amp; Clyde', slug : 'bonnie-clyde', icon : '/Symfony2/web/upload/poster/posters/270110-2.jpg' },
			  				{ value : 'Soukyuu no Fafner', label : 'Soukyuu no Fafner', slug : 'soukyuu-no-fafner', icon : '/Symfony2/web/upload/poster/posters/81110-1.jpg' },
			  				{ value : 'Au nom de la loi', label : 'Au nom de la loi', slug : 'au-nom-de-la-loi', icon : '/Symfony2/web/upload/poster/posters/75724-1.jpg' },
			  				{ value : 'Dead Famous', label : 'Dead Famous', slug : 'dead-famous', icon : '/Symfony2/web/upload/poster/default/dead-famous.jpg' },
			  				{ value : 'Famous, Rich and Hungry', label : 'Famous, Rich and Hungry', slug : 'famous-rich-and-hungry', icon : '/Symfony2/web/upload/poster/default/famous-rich-and-hungry.jpg' },
			  				{ value : 'Famous Planes: Superplanes', label : 'Famous Planes: Superplanes', slug : 'famous-planes-superplanes', icon : '/Symfony2/web/upload/poster/posters/280972-1.jpg' },
			  				{ value : 'Famous Crime Scene', label : 'Famous Crime Scene', slug : 'famous-crime-scene', icon : '/Symfony2/web/upload/poster/default/famous-crime-scene.jpg' },
			  				{ value : 'Famous, Rich and Jobless', label : 'Famous, Rich and Jobless', slug : 'famous-rich-and-jobless', icon : '/Symfony2/web/upload/poster/default/famous-rich-and-jobless.jpg' },
			  				{ value : 'Branson Famous', label : 'Branson Famous', slug : 'branson-famous', icon : '/Symfony2/web/upload/poster/default/branson-famous.jpg' },
			  				{ value : 'Barely Famous', label : 'Barely Famous', slug : 'barely-famous', icon : '/Symfony2/web/upload/poster/default/barely-famous.jpg' },
			  				{ value : 'Famous in 12', label : 'Famous in 12', slug : 'famous-in-12', icon : '/Symfony2/web/upload/poster/posters/279947-1.jpg' },
			  				{ value : 'You Can&#039;t Fire Me, I&#039;m Famous!', label : 'You Can&#039;t Fire Me, I&#039;m Famous!', slug : 'you-can-t-fire-me-i-m-famous', icon : '/Symfony2/web/upload/poster/default/you-can-t-fire-me-i-m-famous.jpg' },
			  				{ value : 'Nearly Famous', label : 'Nearly Famous', slug : 'nearly-famous', icon : '/Symfony2/web/upload/poster/posters/134061-1.jpg' },
			  				{ value : 'Famous Explorers Series', label : 'Famous Explorers Series', slug : 'famous-explorers-series', icon : '/Symfony2/web/upload/poster/default/famous-explorers-series.jpg' },
			  				{ value : 'Famous, Rich and Homeless', label : 'Famous, Rich and Homeless', slug : 'famous-rich-and-homeless', icon : '/Symfony2/web/upload/poster/default/famous-rich-and-homeless.jpg' },
			  				{ value : 'Famous Food', label : 'Famous Food', slug : 'famous-food', icon : '/Symfony2/web/upload/poster/posters/250017-1.jpg' },
			  				{ value : 'After They Were Famous', label : 'After They Were Famous', slug : 'after-they-were-famous', icon : '/Symfony2/web/upload/poster/posters/258030-1.jpg' },
			  				{ value : 'Famous Chil Princesses', label : 'Famous Chil Princesses', slug : 'famous-chil-princesses', icon : '/Symfony2/web/upload/poster/default/famous-chil-princesses.jpg' },
			  				{ value : 'Famous Planes: World War II Fighters', label : 'Famous Planes: World War II Fighters', slug : 'famous-planes-world-war-ii-fighters', icon : '/Symfony2/web/upload/poster/posters/280975-1.jpg' },
			  				{ value : 'Fuck Me, I&#039;m Famous!', label : 'Fuck Me, I&#039;m Famous!', slug : 'fuck-me-i-m-famous', icon : '/Symfony2/web/upload/poster/posters/302260-1.jpg' },
			  				{ value : 'Murder Made Me Famous', label : 'Murder Made Me Famous', slug : 'murder-made-me-famous', icon : '/Symfony2/web/upload/poster/posters/298717-1.jpg' },
			  				{ value : 'Le Club des Cinq : Nouvelles Enquêtes', label : 'Le Club des Cinq : Nouvelles Enquêtes', slug : 'le-club-des-cinq-nouvelles-enquetes', icon : '/Symfony2/web/upload/poster/posters/248249-1.jpg' },
			  				{ value : 'Zach Stone Is Gonna Be Famous', label : 'Zach Stone Is Gonna Be Famous', slug : 'zach-stone-is-gonna-be-famous', icon : '/Symfony2/web/upload/poster/posters/267695-2.jpg' },
			  				{ value : 'Famous and Fearless', label : 'Famous and Fearless', slug : 'famous-and-fearless', icon : '/Symfony2/web/upload/poster/default/famous-and-fearless.jpg' },
			  				{ value : 'Virtually Famous', label : 'Virtually Famous', slug : 'virtually-famous', icon : '/Symfony2/web/upload/poster/posters/284174-2.jpg' },
			  				{ value : 'Famous Generals: Heroes of WWII', label : 'Famous Generals: Heroes of WWII', slug : 'famous-generals-heroes-of-wwii', icon : '/Symfony2/web/upload/poster/posters/249090-1.jpg' },
			  				{ value : 'Armed &amp; Famous', label : 'Armed &amp; Famous', slug : 'armed-famous', icon : '/Symfony2/web/upload/poster/default/armed-famous.jpg' },
			  				{ value : 'Lifestyles of the Rich and Famous', label : 'Lifestyles of the Rich and Famous', slug : 'lifestyles-of-the-rich-and-famous', icon : '/Symfony2/web/upload/poster/default/lifestyles-of-the-rich-and-famous.jpg' },
			  				{ value : 'Le club des cinq (1978)', label : 'Le club des cinq (1978)', slug : 'le-club-des-cinq-1978', icon : '/Symfony2/web/upload/poster/posters/70412-4.jpg' },
			  				{ value : 'Le club des cinq (1996)', label : 'Le club des cinq (1996)', slug : 'le-club-des-cinq-1996', icon : '/Symfony2/web/upload/poster/posters/77665-2.jpg' },
			  				{ value : 'The Famous Teddy Z', label : 'The Famous Teddy Z', slug : 'the-famous-teddy-z', icon : '/Symfony2/web/upload/poster/default/the-famous-teddy-z.jpg' },
			  				{ value : 'I&#039;m Famous and Frightened', label : 'I&#039;m Famous and Frightened', slug : 'i-m-famous-and-frightened', icon : '/Symfony2/web/upload/poster/default/i-m-famous-and-frightened.jpg' },
			  				{ value : 'Beyond Westworld', label : 'Beyond Westworld', slug : 'beyond-westworld', icon : '/Symfony2/web/upload/poster/posters/77993-2.jpg' },
			  				{ value : 'Stranger Things', label : 'Stranger Things', slug : 'stranger-things', icon : '/Symfony2/web/upload/poster/posters/305288-4.jpg' },
			  				{ value : 'The Man in the High Castle', label : 'The Man in the High Castle', slug : 'the-man-in-the-high-castle', icon : '/Symfony2/web/upload/poster/posters/295829-14.jpg' },
			  				{ value : '** 403: Series Not Permitted **', label : '** 403: Series Not Permitted **', slug : '403-series-not-permitted', icon : '/Symfony2/web/upload/poster/default/.jpg' },
			  				{ value : 'Falling Water', label : 'Falling Water', slug : 'falling-water', icon : '/Symfony2/web/upload/poster/posters/311917-5.jpg' },
			  				{ value : '', label : '', slug : '', icon : '/Symfony2/web/upload/poster/posters/296762-3.jpg' },
			  				{ value : '13 Reasons Why', label : '13 Reasons Why', slug : '13-reasons-why', icon : '/Symfony2/web/upload/poster/posters/323168-2.jpg' },
			  				{ value : 'Immortal Grand Prix', label : 'Immortal Grand Prix', slug : 'immortal-grand-prix', icon : '/Symfony2/web/upload/poster/default/.jpg' },
			  				{ value : 'Great Grand Prix Racing Heroes', label : 'Great Grand Prix Racing Heroes', slug : 'great-grand-prix-racing-heroes', icon : '/Symfony2/web/upload/poster/posters/252973-1.jpg' },
			  				{ value : 'Future GPX Cyber Formula', label : 'Future GPX Cyber Formula', slug : 'future-gpx-cyber-formula', icon : '/Symfony2/web/upload/poster/default/.jpg' },
			  				{ value : 'Arrow Emblem Grand Prix no Taka', label : 'Arrow Emblem Grand Prix no Taka', slug : 'arrow-emblem-grand-prix-no-taka', icon : '/Symfony2/web/upload/poster/posters/240711-1.jpg' },
			  				{ value : 'Be a Grand Prix Driver', label : 'Be a Grand Prix Driver', slug : 'be-a-grand-prix-driver', icon : '/Symfony2/web/upload/poster/posters/268605-1.jpg' },
			  				{ value : '', label : '', slug : '-1', icon : '/Symfony2/web/upload/poster/default/ippon-grand-prix.jpg' },
			  				{ value : 'Weeds', label : 'Weeds', slug : 'weeds', icon : '/Symfony2/web/upload/poster/posters/74845-20.jpg' },
			  				{ value : 'Sacred Weeds', label : 'Sacred Weeds', slug : 'sacred-weeds', icon : '/Symfony2/web/upload/poster/posters/138281-1.jpg' },
			      ];
    $( "#serie_name" ).autocomplete({
      source: function(request, response) {
        var results = $.ui.autocomplete.filter(availableTags, request.term);
        
        response(results.slice(0, 8));
    },
	  minLength : 1 ,
	  delay: 200,
	  select : function(event, ui){ // lors de la s�lection d'une proposition
		url = "http://localhost/Symfony2/web/app_dev.php/serie/"+ui.item.slug;
		$(location).attr("href", url);
		}
    });
	$( "#serie_name" ).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
    
    var $li = $('<li>'),
        $img = $('<img>'),
		$span_label = $('<span>');

	$span_label.attr({
		  class: 'text_autocomplete_result'
	});
    $img.attr({
      src: item.icon,
      alt: item.label,
	  class: 'img_autocomplete_result'
    });
	$li.attr({
	  class: 'autocomplete_result'
    });
	$span_label.append(item.label);
    $li.attr('data-value', item.label);
    $li.append('<a href="#"> ');
    $li.find('a').append($img).append($span_label);    

    return $li.appendTo(ul);
  };
});
}