serie_app_formnewserie:
    path:     /search-serie
    defaults: { _controller: SerieDataBundle:Default:addSeries }
    options:
        expose: true
        
serie_app_getserie:
    path:     /get_serie
    defaults: { _controller: SerieAppBundle:Default:getSerie }
    options:
        expose: true