<?php

namespace DataBundle\Repository;

/**
 * callApiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class callApiLogRepository extends \Doctrine\ORM\EntityRepository
{
}
