<?php

namespace DataBundle\Repository;

/**
 * CollectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectedRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUserOrderBy($user, $fieldToOrder)
	{
		$query = 	'
					SELECT c
					FROM DataBundle:Collected c JOIN c.serie s JOIN c.user u 
					WHERE u.id = :user_id 
					';
		if($fieldToOrder == "firstAired")
			$query .= 'ORDER BY s.firstAired	DESC';
		
		$qb = $this->getEntityManager()->createQuery($query);
		$qb->setParameter('user_id', $user->getId());
		return $qb
			->getResult();
	}
}
